name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          #connection_url: ${{ secrets.MAIL_CONNECTION }}
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_MAIL }}
          password: ${{ secrets.MAIL_PASS }}
          subject: Reporte Codee
          to: ${{ secrets.DEST_MAIL }}
          from: ${{ secrets.MAIL_MAIL }}
          body: Reporte adjunto de codee
          attachments: report.html
