name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          #server_address: smtp.gmail.com
          #server_port: 465
          #secure: true
          #username: chesterhomey@gmail.com
          #password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: Reporte Codee
          to: ${{ secrets.MAIL_CONNECTION }}$
          from: ${{ secrets.MAIL_CONNECTION }}$
          body: Reporte adjunto de codee
          attachments: report.html
